
<section class="box"><!--inicio contato-->

<div class="col12">
	<h2 class="tit">Banheiros</h2>
	
	<div class="col8 esq galeria">
		<ul>
			<li>
				<div class="capa">
					<a rel="gallery" class="gallery" href="<?php print $this->baseUrl()?>/public/imgs/banheiros/banheiros_vrio-1.jpg"><img src="<?php print $this->baseUrl()?>/public/imgs/banheiros/thumb-1.jpg" alt="">
					<span><i>+</i></span>
					</a>					
				</div>
			</li>
			<li>
				<div class="capa">
					<a rel="gallery" class="gallery" href="<?php print $this->baseUrl()?>/public/imgs/banheiros/banheiros_vrio-2.jpg"><img src="<?php print $this->baseUrl()?>/public/imgs/banheiros/thumb-2.jpg" alt="">
					<span><i>+</i></span>
					</a>					
				</div>
			</li>
			<li>
				<div class="capa">
					<a rel="gallery" class="gallery" href="<?php print $this->baseUrl()?>/public/imgs/banheiros/banheiros_vrio-3.jpg"><img src="<?php print $this->baseUrl()?>/public/imgs/banheiros/thumb-3.jpg" alt="">
					<span><i>+</i></span>
					</a>					
				</div>
			</li>
			<li>
				<div class="capa">
					<a rel="gallery" class="gallery" href="<?php print $this->baseUrl()?>/public/imgs/banheiros/banheiros_vrio-4.jpg"><img src="<?php print $this->baseUrl()?>/public/imgs/banheiros/thumb-4.jpg" alt="">
					<span><i>+</i></span>
					</a>					
				</div>
			</li>
			<li>
				<div class="capa">
					<a rel="gallery" class="gallery" href="<?php print $this->baseUrl()?>/public/imgs/banheiros/banheiros_vrio-5.jpg"><img src="<?php print $this->baseUrl()?>/public/imgs/banheiros/thumb-5.jpg" alt="">
					<span><i>+</i></span>
					</a>					
				</div>
			</li>
			<li>
				<div class="capa">
					<a rel="gallery" class="gallery" href="<?php print $this->baseUrl()?>/public/imgs/banheiros/banheiros_vrio-7.jpg"><img src="<?php print $this->baseUrl()?>/public/imgs/banheiros/thumb-7.jpg" alt="">
					<span><i>+</i></span>
					</a>					
				</div>
			</li>
			<li>
				<div class="capa">
					<a rel="gallery" class="gallery" href="<?php print $this->baseUrl()?>/public/imgs/banheiros/banheiros_vrio-8.jpg"><img src="<?php print $this->baseUrl()?>/public/imgs/banheiros/thumb-8.jpg" alt="">
					<span><i>+</i></span>
					</a>					
				</div>
			</li>
			<li>
				<div class="capa">
					<a rel="gallery" class="gallery" href="<?php print $this->baseUrl()?>/public/imgs/banheiros/banheiros_vrio-9.jpg"><img src="<?php print $this->baseUrl()?>/public/imgs/banheiros/thumb-9.jpg" alt="">
					<span><i>+</i></span>
					</a>					
				</div>
			</li>
			<li>
				<div class="capa">
					<a rel="gallery" class="gallery" href="<?php print $this->baseUrl()?>/public/imgs/banheiros/banheiros_vrio-10.jpg"><img src="<?php print $this->baseUrl()?>/public/imgs/banheiros/thumb-10.jpg" alt="">
					<span><i>+</i></span>
					</a>					
				</div>
			</li>
			<li>
				<div class="capa">
					<a rel="gallery" class="gallery" href="<?php print $this->baseUrl()?>/public/imgs/banheiros/banheiros_vrio-11.jpg"><img src="<?php print $this->baseUrl()?>/public/imgs/banheiros/thumb-11.jpg" alt="">
					<span><i>+</i></span>
					</a>					
				</div>
			</li>
			
		</ul>
	</div>
	<div class="col4 tratamento">
		<h2 class="tit">Tratamento de dejetos</h2>
		<p>A Vrio também trabalha na coleta e no transporte de resíduos industriais, comerciais e residenciais.</p>
		<p>Os resíduos provenientes dos banheiros químicos e das fossas industriais são descartados em uma ETE (Estação de Tratamento de Efluentes) devidamente legalizada junto  ao CPRH e demais órgãos competentes.</p>
		<img src="<?php print $this->baseUrl()?>/public/imgs/caminhao.jpg" alt="">
	</div>

</div>



</section><!--fim contato-->
