
    <section class="box clearfix">
      
      	<div class="col12 home">
       	    <a class="localizar" href="<?php print $this->baseUrl()?>/index/localizar-banheiros">Encontre os banheiros mais perto de você</a>
            <ul class="bxslider">
              <li><img src="<?php print $this->baseUrl()?>/public/imgs/caminhao-banheiro.png" /></li>
              <li><img src="<?php print $this->baseUrl()?>/public/imgs/banheiro-interno.png" /></li>
              <li><img src="<?php print $this->baseUrl()?>/public/imgs/entrada-banheiro.png" /></li>
            </ul>
       	
       	</div>

    </section>
 
