
<section class="box"><!--inicio contato-->

<div class="col12">
	<h2 class="tit">quem somos</h2>
<div class="col7 esq">
	<p>A Risco Zero Autos iniciou suas atividades em 26 de Março de 2001 através do pioneirismo e da visão empresarial do Sr. Jose Ricardo Mota Rago, que vislumbrou  excelentes perspectivas de negócios na transformação de veículos  e serviços embarcados por meio de unidades móveis para o mercado brasileiro.</p>
	 
	<p>No início para desenvolver seus projetos , a empresa firmou uma parceria com o grupo de concessionárias Via sul, e passamos juntos 10 anos ,construímos varias soluções sobre rodas durante esse tempo.</p>
	
	<h2 class="tit">A EVOLUÇÃO</h2>
	<p>A partir de  2009  nossa empresa estava preparada para ganhar espaço, passamos a comercializar veículos transformados diretamente para vários clientes no setor público em todo território nacional, em 2010 a Risco Zero em Parceria com o Grupo Avantia tecnologia em vídeo monitoramento, desenvolveu 5 unidades móveis de vídeo monitoramento, atendendo a Policia Militar de Pernambuco  no carnaval , objetivando a redução da criminalidade sendo  o resultado muito eficaz.</p>

	<h2 class="tit">ATUALMENTE</h2>
	 
	<p>A Risco Zero Autos,  desenvolveu um modelo de unidade móvel  denominada, " Banheiros Vrio "com lançamento programado para carnaval de 2014 que pretende revolucionar as condições de bem estar social  nas grandes aglomerações, seu nome sendo criado em 4 pilares VRIO ( VALOR, RARO, INIGUALAVEL E ORGANIZAVEL).</p>
	 
	<p>Com base na solidez e dispostos a apresentar sempre as melhores soluções para a sua empresa, a Banheiros VRIO acredita na inovação. Investe permanentemente em desenvolvimento e atualização tecnológica, agregando cada vez mais valores aos produtos e serviços comercializados.</p>

</div>

<div class="col5 dir">

	 
	<h2 class="tit">Nossos Objetivos</h2>
	
	<p>Atender e satisfazer as necessidades de nossos clientes, fornecendo produtos com a mais alta qualidade, tecnologia e pontualidade, superando-as quando possível, para manter sua fidelidade.
		Buscar o comprometimento de nossos colaboradores objetivando atingir as metas e resultados, para dar continuidade e obtenção de recursos necessários para o desenvolvimento da empresa.</p>
	
	<p>A maioria dos usuários de sanitários públicos estão insatisfeitos com as instalações disponíveis atualmente. A preocupação com a higiene, privacidade e segurança são os aspectos mais importantes para a Banheiros VRIO.</p>
	 
	<p>Desta forma com a visão de manter-se imprescindível por meio de participações expressivas no mercado interno, pensando sempre em desenvolver soluções inovadoras móveis para o bem estar da sociedade.</p>
</div>

</div>

</section><!--fim contato-->
