
<section class="box"><!--inicio contato-->

<div class="col12">
	<h2 class="tit">TERMO DE ADESÃO E USO DO SISTEMA DE BANHEIROS VRIO</h2>
	<div class="col10 esq">
		
		<div class=WordSection1>

			<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
			 style='width:100.0%;mso-cellspacing:0cm;mso-yfti-tbllook:1184;mso-padding-alt:
			 0cm 0cm 0cm 0cm'>
			 <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:yes'>
			  <td width="100%" style='width:100.0%;padding:0cm 0cm 0cm 0cm'>
			  <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%"
			   style='width:100.0%;mso-cellspacing:0cm;mso-yfti-tbllook:1184;mso-padding-alt:
			   0cm 0cm 0cm 0cm'>
			   <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:yes'>
			    <td style='padding:0cm 0cm 0cm 0cm'>
			    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
			    .0001pt;text-align:center;line-height:normal'><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p>&nbsp;</o:p></span></p>
			    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
			    .0001pt;text-align:center;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'></span></b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:
			    .0001pt;text-align:center;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>&nbsp;</span></b><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>&nbsp;</span></b><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>1.
			    DAS DEFINI‚ÍES</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>1.1. S‹o aplic‡veis
			    as seguintes defini›es:</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>I
			    - DO ATENDIMENTO</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: para a utiliza‹o do
			    Sistema de Banheiros VRIO, a CONTRATADA oferece ao USUçRIO facilidades na
			    aquisi‹o dos ACESSOS (por meio de pulseiras de identifica‹o) atravŽs do
			    site </span><span lang=PT-BR><a href="http://www.banheirosvrio.com.br"><span
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>www.banheirosvrio.com.br</span></a></span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>,
			    atravŽs do APP pr—prio dispon’vel para sistema <i style='mso-bidi-font-style:
			    normal'>Androide</i> e <i style='mso-bidi-font-style:normal'>IOS </i>sem a
			    necessidade de falar diretamente com atendentes ou telefonistas, alŽm dos
			    pontos fixos de vendas;</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>i.i
			    - SITE WAP OU APP</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: site de internet </span><span
			    lang=PT-BR><a href="http://www.banheirosvrio.com.br"><span
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>www.banheirosvrio.com.br</span></a></span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>
			    ou software aplicativo dispon’vel para aparelhos celulares denominado
			    Banheiros VRIO, como meio de auto-atendimento pelos USUçRIOS do sistema
			    para a aquisi‹o dos ACESSOS de acesso aos Banheiros VRIO (localiza‹o
			    dispon’vel no site e no APP), mediante a retirada das pulseiras de
			    identifica‹o em locais prŽ-determinados;</span><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>i.ii
			    - PONTOS FIXOS DE VENDAS</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: as vendas dos
			    acessos (pulseiras de identifica‹o) ser‹o feitas nos pr—prios Banheiros
			    VRIO, alŽm de pontos de vendas alternativos com localiza‹o de cada um
			    deles dispon’vel no site </span><span lang=PT-BR><a
			    href="http://www.banheirosvrio.com.br"><span style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>www.banheirosvrio.com.br</span></a></span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'> e
			    no APP Banheiros VRIO;</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>II
			    &#8211; DO CADASTRO DOS USUçRIOS NO SITE E NO APP</span></b><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: O
			    USUçRIO, pessoa f’sica ou jur’dica, dever‡ preencher formul‡rio eletr™nico
			    pr—prio da CONTRATADA com os seus dados cadastrais; o cadastro dever‡ ser
			    feito apenas pelos Usu‡rios do site ou do APP, onde dever‹o cadastrar o nœmero
			    do telefone de contato com DDD no campo &quot;Telefone de Contato&quot; do
			    cadastro pessoal de cada USUçRIO, alŽm de cadastrar uma senha criada pelo
			    pr—prio Usu‡rio. O cadastro efetivado propiciar‡ a compra dos PASSES
			    (pulseiras de identifica‹o) no site ou no APP do Sistema de Banheiros VRIO;<o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>ii.i
			    - SENHA</span></b><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-bidi-font-family:
			    Arial;mso-fareast-language:PT-BR'>: assinatura por meio eletr™nico, formada
			    por caracteres alfanumŽricos, criada e modificada a qualquer momento
			    unicamente pelo USUçRIO e sob sua responsabilidade;</span><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>III
			    &#8211; DA CONTRATADA</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: </span><b
			    style='mso-bidi-font-weight:normal'><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow"'>RISCO ZERO AUTO CENTER LTDA - EPP</span></b><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow"'>, pessoa
			    jur’dica de direito privado, inscrita no CNPJ sob o n.¼ 04.994.767/0001-34,
			    com estabelecimento empresarial na <span style='mso-bidi-font-weight:bold'>Av.
			    Senador Nilo Coelho, n.¼ 186, bairro de Peixinhos, Olinda-PE, CEP&nbsp;53.260-555</span></span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>,
			    empresa que produz, instala, implanta e administra o uso dos BANHEIROS VRIO,
			    tambŽm respons‡vel pela venda e controle dos acessos (pulseiras de
			    identifica‹o) dos usu‡rios aos BANHEIROS VRIO, assim como pela opera‹o,
			    manuten‹o e limpeza dos BANHEIROS VRIO.<o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>IV
			    &#8211; PROVEDOR:</span></b><span lang=PT-BR style='font-size:8.5pt;
			    font-family:Arial;mso-fareast-font-family:"Times New Roman";color:#7C7C7C;
			    background:#F2F2F2;mso-ansi-language:EN-US'> </span><b><span
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-ansi-language:EN-US;
			    mso-fareast-language:PT-BR'>UNIVERSO ONLINE S/A - CNPJ/MF
			    01.109.184/0001-95 - Av. <span class=SpellE>Brigadeiro</span> <span
			    class=SpellE>Faria</span> Lima, 1.384, S‹o Paulo - SP - CEP 01452-002</span></b><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>,
			    empresa especializada em transa›es eletr™nicas para servios de utiliza‹o
			    dos BANHEIROS VRIO;</span><b><span style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-bidi-font-family:
			    Arial;mso-ansi-language:EN-US;mso-fareast-language:PT-BR'><o:p></o:p></span></b></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>V
			    &#8211; EXTRATO DE MOVIMENTA‚ÌO</span></b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>:
			    documento eletr™nico exibido no site&nbsp;</span><span lang=PT-BR><a
			    href="http://www.banheirosvrio.com.br"><span style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>www.banheirosvrio.com.br</span></a></span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'> do
			    sistema de BANHEIROS VRIO e no APP Banheiros VRIO, onde s‹o discriminados
			    os dŽbitos e crŽditos relativos ˆs TRANSA‚ÍES realizadas pelo USUçRIO, tais
			    como, compra de crŽditos de ACESSOS (pulseiras de identifica‹o) e dŽbitos quando
			    da sua utiliza‹o;</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>VI
			    &#8211; UTILIZA‚ÌO AO SISTEMA DE BANHEIROS VRIO</span></b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: a
			    utiliza‹o do sistema de BANHEIROS VRIO se dar‡ atravŽs da aquisi‹o de ACESSOS
			    (pulseiras de identifica‹o) atravŽs do site </span><span lang=PT-BR><a
			    href="http://www.banheirosvrio.com.br"><span style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>www.banheirosvrio.com.br</span></a>,</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>
			    do APP Banheiros VRIO ou nos pontos fixos de vendas, e dar‡ direito ˆ
			    utiliza‹o em qualquer unidade (Banheiro) do Sistema de BANHEIROS VRIO,
			    cujas localiza›es est‹o identificadas no Site e no APP, por um dia, num per’odo
			    das 6:00 ˆs 4:00 do dia seguinte, respeitando o hor‡rio de opera‹o,
			    manuten‹o, limpeza e as regras contratuais. Fica o Usu‡rio que adquiriu o ACESSO
			    (pulseira de identifica‹o) sujeito a fila, se houver, para a utiliza‹o do
			    Banheiro VRIO.</span><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-fareast-language:
			    PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>VII
			    &#8211; BANHEIROS VRIO</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: denomina‹o de
			    fantasia do sistema de banheiros qu’micos m—veis, constru’dos sobre chassi do
			    tipo trailer, totalmente climatizados, ilumina‹o pr—pria, limpos e
			    perfumados mediante servio de limpeza com ‡lcool em gel. Os Banheiros VRIO
			    atendem as regras do meio ambiente e destinam os dejetos para unidades de tratamento
			    de esgoto. As unidades dos Banheiros VRIO estar‹o localizadas em pontos
			    estratŽgicos na Cidade de Olinda-PE e Recife Antigo e garantir‹o ao usu‡rio
			    um servio de qualidade e comodidade, atravŽs da aquisi‹o dos ACESSOS (pulseiras)
			    pelo <i style='mso-bidi-font-style:normal'>site</i>, APP e nos pontos fixos
			    de vendas;</span><span lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";
			    mso-fareast-font-family:"Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>VIII
			    &#8211; TERMO DE ADESÌO E USO</span></b><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: o presente
			    instrumento;</span><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-fareast-language:
			    PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>viii.i
			    &#8211; TRANSA‚ÌO</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: toda e qualquer
			    utiliza‹o eletr™nica, aquisi‹o de bens e/ou servios efetuados nos
			    ambientes de relacionamento eletr™nico do sistema de Banheiros VRIO,
			    incluindo outros lanamentos previstos neste TERMO DE ADESÌO E USO;</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>viii.ii
			    &#8211; LAN‚AMENTOS</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: valor debitado no
			    cart‹o de crŽdito e/ou dŽbito, informado pelo USUçRIO, relativos ˆ aquisi‹o
			    dos ACESSOS (pulseiras de identifica‹o) para utiliza‹o do sistema de
			    Banheiros VRIO;</span><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-fareast-language:
			    PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>viii.iii
			    &#8211; OPERADORA DE CARTÌO DE CRƒDITO</span></b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>:
			    empresa operadora da ÒbandeiraÓ do Cart‹o de CrŽdito do USUçRIO e
			    habilitada no site do sistema de Banheiros VRIO;</span><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>viii.iv
			    &#8211; SERVI‚OS</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: Utiliza‹o do
			    sistema de Banheiros VRIO, localizados nas cidades de Recife e Olinda, no
			    per’odo do Carnaval 2014, compreendido do dia 28 de Fevereiro a 04 de Maro
			    do ano de 2014, sendo v‡lida a utiliza‹o de cada ACESSO (pulseira de
			    identifica‹o) por um dia, que compreender‡ das 6:00 ˆs 4:00 do dia
			    seguinte, sendo identificadas as pulseiras por cores distintas para cada
			    dia;</span><span lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";
			    mso-fareast-font-family:"Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>viii.v
			    &#8211; TAXA DE INSCRI‚ÌO</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: valor pago pelo USUçRIO
			    para ter acesso ao sistema de Banheiros VRIO no per’odo carnavalesco de
			    2014, na import‰ncia de R$ 10,00 (dez reais) por ACESSO (pulseira de
			    identifica‹o), sendo v‡lida sua utiliza‹o no per’odo de 6:00 do dia de
			    utiliza‹o atŽ as 4:00 do dia seguinte, em qualquer dos Banheiros VRIO
			    dispon’veis. A pulseira de acesso Ž pessoal e intransfer’vel ao sistema de
			    Banheiros VRIO. O zelo e a conserva‹o da pulseira de identifica‹o para
			    utiliza‹o dos Banheiros VRIO Ž de responsabilidade do USUçRIO, n‹o sendo
			    substitu’da ou fornecida uma nova no caso de rompimento ou perda da mesma;</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>IX
			    &#8211; BANHEIRO VRIO &#8211; UNIDADES</span></b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>:
			    mobili‡rio urbano da CONTRATADA, estacionado nas praas e logradouros
			    pœblicos, onde s‹o utilizados os Banheiros VRIO pelos usu‡rios nos termos
			    do presente Termo;</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>X
			    &#8211; HORçRIO DE OPERA‚ÌO</span></b><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>: os Banheiros VRIO
			    estar‹o dispon’veis para utiliza‹o em diversas localidades nas Cidades de
			    Recife e Olinda no per’odo do carnaval 2014, e funcionar‹o 24 (vinte e
			    quatro) horas por dia, respeitando o tempo de 4 (quatro) horas por dia para
			    a limpeza e conserva‹o das unidades;</span><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>2.
			    DA ADESÌO E USO DO SISTEMA DE BANHEIROS VRIO.</span></b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>2.1. A CONTRATADA
			    fornece ao USUçRIO, sujeito aos Termos de Uso abaixo, a PRESTA‚ÌO de
			    SERVI‚OS relativos ao Sistema de Banheiros VRIO, de acordo com as
			    informa›es e procedimentos disponibilizados em seu site de servio (</span><span
			    lang=PT-BR><a href="http://www.banheirosvrio.com"><span style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>www.banheirosvrio.com</span></a></span><u><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;color:blue;mso-fareast-language:
			    PT-BR'>.br</span></u><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-bidi-font-family:
			    Arial;mso-fareast-language:PT-BR'>) por meio eletr™nico de transmiss‹o ˆ
			    dist‰ncia de dados via Internet.</span><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>2.2. Os SERVI‚OS
			    poder‹o ser modificados ou extintos a qualquer momento. Em qualquer
			    hip—tese de modifica‹o ou extin‹o dos SERVI‚OS, o USUçRIO ser‡
			    devidamente informado deste ato quando do acesso de consulta do site do
			    sistema e/ou pelo APP Banheiros VRIO, alŽm de consulta do Portal de
			    Relacionamento da CONTRATADA.</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>2.2.1. Em havendo
			    modifica›es, ficam ressalvados os crŽditos e demais servios adquiridos e
			    ainda n‹o utilizados por parte do USUçRIO.</span><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>2.3. Ap—s marcar a
			    op‹o &quot;Eu aceito e concordo&quot;, o USUçRIO declara que leu e
			    concordou expressamente com a vers‹o mais recente do Termo de Ades‹o e Uso,
			    fato este que vincular‡ automaticamente o USUçRIO ˆs regras aqui contidas.</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>3.
			    DESCRI‚ÌO DO SERVI‚O</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>3.1 O USUçRIO est‡
			    ciente e concorda que os SERVI‚OS s‹o fornecidos na forma como se encontram
			    disponibilizados.</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>3.2 Os SERVI‚OS s‹o
			    disponibilizados para o Usu‡rio atravŽs do acesso ˆ internet do Site do
			    Sistema de Banheiros VRIO (</span><span lang=PT-BR><a
			    href="http://www.banheirosvrio.com"><span style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>www.banheirosvrio.com</span></a></span><u><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;color:blue;mso-fareast-language:
			    PT-BR'>.br</span></u><u><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>)</span></u><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>,
			    ou atravŽs do telefone celular via WAP, APP Banheiros VRIO ou PORTAL DE VOZ
			    (81) 4141.6398, bem como em todas as Unidades do Sistema de Banheiros VRIO e
			    pontos de vendas fixos, implantadas no Estado de Pernambuco;</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>3.3 AtravŽs deste
			    Site o USUçRIO poder‡ realizar as seguintes opera›es:</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>I - Cadastramento e
			    atualiza‹o de dados pessoais; II - Aquisi‹o de ACESSOS (pulseiras de
			    identifica‹o) para utiliza‹o sistema; III - Consultas de saldos e
			    extratos e movimenta›es; IV - Localiza‹o das Unidades dos Banheiros VRIO;
			    V - Consultar disponibilidade de ACESSOS (pulseiras de identifica‹o) para aquisi‹o;
			    VI - Outros servios de uso geral disponibilizados, tais como: Localiza‹o
			    dos pontos fixos de vendas de ACESSOS ao Sistema de Banheiros VRIO e pontos
			    de trocas do Voucher pela pulseira de ACESSO ao Sistema de Banheiros VRIO.<o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>3.4 O Usu‡rio fica
			    desde logo informado e concorda que os SERVI‚OS deste Site estar‹o dispon’veis
			    24 (vinte e quatro) horas por dia, 7 (sete) dias por semana, mas que por
			    motivos alheios ˆ vontade da CONTRATADA (caso fortuito e/ou fora maior),
			    nestes inclu’dos a manuten‹o dos servidores, os mesmo poder‹o estar
			    indispon’veis para consultas e compras de ACESSOS (pulseiras de
			    identifica‹o) ao Sistema de Banheiros VRIO.<o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>3.5 Cada ACESSO
			    (pulseira de identifica‹o) dar‡ direito ˆ retirada de uma òNICA pulseira
			    para utiliza‹o do Sistema de Banheiros VRIO pelo dia escolhido no ato da
			    aquisi‹o.</span><span lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";
			    mso-fareast-font-family:"Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>3.10 Para utiliza‹o
			    do Sistema de Banheiros VRIO, o USUçRIO de posse de um <i style='mso-bidi-font-style:
			    normal'>voucher</i> de Acesso ao Sistema de Banheiros VRIO e Documento de
			    Identifica‹o, dever‡ se dirigir a um dos pontos de trocas previamente
			    definidos e informados no site (<a href="http://www.banheirosvrio.com.br">www.banheirosvrio.com.br</a>)
			    e no APP Banheiros VRIO e retirar sua Pulseira de Identifica‹o, para ter
			    acesso aos Banheiros VRIO;</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>4.
			    DO PAGAMENTO</span></b><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-bidi-font-family:
			    Arial;mso-fareast-language:PT-BR;mso-bidi-font-weight:bold'>: Para
			    pagamento das transa›es decorrentes do uso do sistema de Banheiros VRIO, o
			    USUçRIO autoriza a CONTRATADA a fazer lanamentos no cart‹o de crŽdito ou
			    dŽbito informado pelo Usu‡rio, atravŽs do site ou do APP, para pagamento do
			    valor de R$ 10,00 (dez reais) referentes a um ACESSO (pulseira de
			    identifica‹o), que dar‡ direito a utiliza‹o do Sistema de Banheiros VRIO
			    no per’odo de 24 horas, respeitando o tempo de 4 (quatro) horas para
			    manuten‹o e limpeza das unidades.<o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR;mso-bidi-font-weight:
			    bold'>4.1 Ao realizar a aquisi‹o do ACESSO (pulseira de identifica‹o), o
			    Usu‡rio dever‡ escolher o dia de sua utiliza‹o.<o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR;mso-bidi-font-weight:
			    bold'>4.2 No caso de aquisi‹o prŽvia do ACESSO ao Sistema de Banheiros
			    VRIO, o Usu‡rio que desejar realizar a troca do dia de utiliza‹o do
			    sistema dever‡ entrar em contato com a CONTRATADA para solicitar a
			    substitui‹o do Acesso mediante o pagamento de 50% (cinquenta por cento) do
			    valor do Acesso, e sujeito a disponibilidade de acessos para o novo dia
			    escolhido. <b><span style="mso-spacerun:yes">&nbsp;</span></b><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>4.3 A CONTRATADA
			    reserva-se o direito de modificar, sem prŽvio aviso, os valores dos acessos
			    (pulseiras de identifica‹o) que est‹o contidos no site do sistema de
			    acordo com as necessidades mercadol—gicas, garantindo a validade e os
			    valores dos ACESSOS, j‡ adquiridos pelos USUçRIOS.</span><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>4.4 O Usu‡rio poder‡
			    acessar, atravŽs de um telefone celular, o SITE WAP OU APP, ou discar para
			    o nœmero do PORTAL DE VOZ (81) 4141.6398, para realizar os seguintes
			    procedimentos:</span><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-fareast-language:
			    PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>a) acessar o servio
			    de VOZ para informa›es de retiradas das pulseiras de identifica‹o e
			    outras informa›es sobre o sistema de Banheiros VRIO; <o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>b) acessar
			    informa›es sobre a disponibilidade de ACESSOS (pulseiras de identifica‹o)
			    para cada dia; <o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>c) falar com a central
			    de atendimento ao usu‡rio.</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>4.5
			    Responsabilidades e Riscos do USUçRIO.</span><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>4.5.1 A CONTRATADA
			    n‹o se responsabilizar‡, em hip—tese alguma, por furto ou perdas de objetos
			    no interior das unidades do Sistema de Banheiros VRIO.</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>4.5.2 O Usu‡rio Ž
			    obrigado a declarar eventuais avarias e/ou danos ocorridos durante o seu
			    uso, informando ao respons‡vel pela unidade do Sistema de Banheiros VRIO.</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>4.5.3 O Usu‡rio tem
			    plena conscincia que Ž de sua œnica e inteira responsabilidade o cuidado
			    com a Pulseira de Identifica‹o para acesso ao Sistema de Banheiros VRIO,
			    sendo proibido, emprestar, sublocar, doar, vender e/ou qualquer outro tipo
			    de atitude vinculada a essas a›es; <o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>5.
			    DEMAIS OBRIGA‚ÍES DO USUçRIO</span></b><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>5.1 O Usu‡rio do
			    sistema compromete-se a fazer sugest›es, reclama›es e outras opini›es
			    gerais sobre o sistema;</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>5.2 Pagar pelo uso
			    de servio;</span><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-fareast-language:
			    PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>5.3 Em hip—tese
			    alguma, a CONTRATADA ser‡ respons‡vel pela perda da senha ou utiliza‹o
			    desta por outrem.</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>6.
			    OBRIGA‚ÍES DE REGISTRO DO USUçRIO</span></b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>6.1 Com vistas ˆ
			    utiliza‹o dos SERVI‚OS, de acordo com os termos deste Termo de Uso, o
			    USUçRIO se obriga a fornecer, quando do seu registro, informa›es pessoais
			    verdadeiras e atuais, inclusive os dados do seu cart‹o de crŽdito ou dŽbito,
			    no diret—rio eletr™nico do site&nbsp;</span><span lang=PT-BR><a
			    href="http://www.banheirosvrio.com.br"><span style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>www.banheirosvrio.com.br</span></a></span><u><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;color:blue;mso-fareast-language:
			    PT-BR'> </span></u><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-bidi-font-family:
			    Arial;mso-fareast-language:PT-BR'>ou no APP Banheiros VRIO, sendo que o
			    mesmo USUçRIO desde logo autoriza a manuten‹o destas informa›es em banco
			    de dados da CONTRATADA. A CONTRATADA TERç O DIREITO DE SUSPENDER A
			    UTILIZA‚ÌO DOS SERVI‚OS PARA O USUçRIO CASO VERIFIQUE, POR QUAISQUER MEIOS,
			    QUE AS INFORMA‚ÍES PRESTADAS PELO USUçRIO SÌO FALSAS OU IRREAIS,
			    INDEPENDENTEMENTE DE NOTIFICA‚ÌO PRƒVIA AO USUçRIO.</span><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>6.2 A CONTRATADA poder‡
			    fornecer as informa›es do USUçRIO para terceiros nos seguintes casos: I -
			    por determina‹o Judicial; II - em atendimento a requerimento do MinistŽrio
			    Pœblico ou Autoridade Policial; III - para garantir a n‹o viola‹o de
			    direitos de terceiros; IV - para garantir a observ‰ncia pelos USUçRIOS
			    deste TERMO ADESÌO E USO.</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>7.
			    DIREITO AUTORAL</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>7.1 O USUçRIO
			    reconhece e concorda que todo o conteœdo dos Sites de internet publicados
			    pelo sistema de Banheiros VRIO, Ž protegido pela Lei de Direito Autoral
			    (Lei 9.610/98), bem como tratados internacionais aplic‡veis a matŽria.
			    Nesse sentido, o USUçRIO se compromete a respeitar tais direitos, bem como
			    se obriga a utilizar os SERVI‚OS apenas para fins de consulta e uso
			    particular, SENDO EXPRESSAMENTE VEDADA A UTILIZA‚ÌO DOS SERVI‚OS PARA
			    QUAISQUER OUTROS FINS, INCLUSIVE COMERCIAIS, SEM PRƒVIA E EXPRESSA
			    AUTORIZA‚ÌO DA CONTRATADA.</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>8.
			    INDENIZA‚ÌO</span></b><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-fareast-language:
			    PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>8.1 O Usu‡rio
			    concorda em indenizar a CONTRATADA de qualquer dano que esta venha a sofrer
			    como consequncia de culpa ou dolo na utiliza‹o irregular ou ilegal dos servios.</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>9.
			    VIGæNCIA, RENOVA‚ÌO E RESCISÌO</span></b><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>9.1 Este CONTRATO
			    ter‡ inicio na data de ades‹o ao SISTEMA pelo USUçRIO para cada ACESSO de
			    utiliza‹o do sistema de Banheiros VRIO, na forma prevista no subitem 2.3
			    deste CONTRATO, e vigorar‡ por um per’odo de um dia para cada Acesso, com
			    in’cio ˆs 6:00 e tŽrmino ˆs 4:00 do dia seguinte, respeitando o tempo de 4 (quatro)
			    horas para servio de manuten‹o e limpeza nas unidades;</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>9.1.2 Para fins de
			    aplica‹o do item anterior s‹o aceitas quaisquer tipo de comunica‹o,
			    inclusive liga›es telef™nicas, por fax ou por e-mail;</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>9.2. O presente
			    contrato ser‡ rescindido de pleno direito caso ocorra expresso e comum
			    acordo entre as partes.</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>9.2.1 O Usu‡rio
			    poder‡ rescindir o presente contrato, com a quita‹o das obriga›es
			    assumidas.</span><span lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";
			    mso-fareast-font-family:"Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>9.2.2 Fica a
			    critŽrio da CONTRATADA a rescis‹o imediata deste CONTRATO, a qualquer
			    tempo, independentemente de qualquer tipo de comunica‹o prŽvia ao Usu‡rio,
			    ocorrendo uma das seguintes hip—teses:</span><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>a) descumprimento de
			    cl‡usula contratual; b) o n‹o pagamento dos servios contratados pelo Usu‡rio;
			    c) decreta‹o de insolvncia ou falncia, no caso de contrata‹o por pessoa
			    jur’dica; c) rescis‹o ou encerramento do termo de autoriza‹o firmado entre
			    a CONTRATADA e a pessoa que autorizou a execu‹o do presente servio; d)
			    por determina‹o legal ou judicial.</span><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>10.
			    ANUNCIANTES</span></b><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-fareast-language:
			    PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>10.1 O USUçRIO
			    concorda e reconhece que a CONTRATADA disponibiliza para o USUçRIO t‹o
			    somente os SERVI‚OS discriminados neste TERMO DE ADESÌO E USO. Assim sendo,
			    eventuais negocia›es ou participa›es do USUçRIO, em promo›es veiculadas
			    por anunciantes, presentes no Site ou APP onde s‹o acessados os SERVI‚OS,
			    incluindo pagamento ou entrega de bens e servios, condi›es, garantias e
			    apresenta›es associadas a tal negocia‹o, ocorrem exclusivamente, por
			    conta e responsabilidade do USUçRIO e do anunciante. O USUçRIO concorda que
			    a CONTRATADA n‹o Ž respons‡vel por quaisquer preju’zos origin‡rios da falha
			    ou falta de qualquer servio/produto disponibilizado pelos anunciantes.</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>11.
			    LINKS</span></b><span lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";
			    mso-fareast-font-family:"Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>11.1 O USUçRIO
			    reconhece e concorda que a CONTRATADA n‹o ser‡ respons‡vel, pelo conteœdo,
			    propaganda, produtos, servios ou outros materiais contidos ou
			    disponibilizados pelos anunciantes, atravŽs de links contidos no site ou APP
			    onde o servio est‡ sendo disponibilizado.</span><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>12.
			    RESPONSABILIDADE</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>12.1 A CONTRATADA
			    n‹o poder‡ ser responsabilizada por qualquer falha ou n‹o funcionamento dos
			    servios provenientes de terceiros ou decorrentes de caso fortuito ou fora
			    maior.</span><span lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";
			    mso-fareast-font-family:"Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>13.
			    DISPOSI‚ÍES GERAIS</span></b><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>13.1 A n‹o
			    exigncia, por qualquer uma das partes, do cumprimento de qualquer cl‡usula
			    ou condi‹o estabelecida, ser‡ considerada mera toler‰ncia, n‹o implicando
			    na sua nova‹o, e t‹o pouco na abdica‹o do direito de exigi-la no futuro,
			    n‹o afetando a validade deste instrumento e quaisquer de suas condi›es.</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>13.2 Os regulamentos
			    relativos a eventuais campanhas promocionais, propagandas de incentivo e
			    outros programas que propiciem benef’cios adicionais ao USUçRIO ser‹o
			    divulgados separadamente, sendo que, por mera liberalidade, alguns servios
			    poder‹o ser oferecidos gratuitamente ou com varia›es dos preos e
			    condi›es regularmente ofertados a t’tulo promocional e por prazo
			    determinado.</span><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-fareast-language:
			    PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>13.3 Na hip—tese de
			    qualquer uma das disposi›es deste contrato vir a ser considerada contr‡ria
			    ˆ lei brasileira, por qualquer autoridade governamental ou decis‹o
			    judicial, as demais disposi›es n‹o afetadas continuar‹o em vigor e as
			    partes dever‹o alterar este instrumento de forma a adequ‡-lo a tal lei ou ˆ
			    decis‹o judicial.</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>13.4 Este contrato
			    obriga as partes e seus sucessores a qualquer t’tulo, constituindo-se em
			    t’tulo executivo extrajudicial, nos termos do artigo 585, inciso II do
			    C—digo de Processo Civil.</span><span lang=PT-BR style='font-size:13.0pt;
			    font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>13.5. O USUçRIO
			    CADASTRADO autoriza a CONTRATADA utilizar recursos de envio de mensagens
			    eletr™nicas para o endereo do e-mail e/ou nœmero do telefone celular cadastrado
			    pelo USUçRIO, necess‡rios a execu‹o dos servios contratados.</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><b><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>14.
			    DO FORO</span></b><span lang=PT-BR style='font-size:13.0pt;font-family:
			    "Arial Narrow";mso-fareast-font-family:"Times New Roman";mso-fareast-language:
			    PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;
			    text-align:justify;line-height:normal'><span lang=PT-BR style='font-size:
			    13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:"Times New Roman";
			    mso-bidi-font-family:Arial;mso-fareast-language:PT-BR'>14.1 As partes
			    elegem o foro da Comarca da Cidade de Recife, Estado de Pernambuco para
			    dirimir eventuais dœvidas ou controvŽrsias decorrentes do presente
			    Contrato, excluindo-se qualquer outro, por mais privilegiado que seja.</span><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p></o:p></span></p>
			    <p class=MsoNormal style='line-height:normal'><span lang=PT-BR
			    style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'><o:p>&nbsp;</o:p></span></p>
			    <p class=MsoNormal align=center style='text-align:center;line-height:normal'><span
			    lang=PT-BR style='font-size:13.0pt;font-family:"Arial Narrow";mso-fareast-font-family:
			    "Times New Roman";mso-fareast-language:PT-BR'>Recife-PE, 03 de fevereiro de
			    2014.<o:p></o:p></span></p>
			    </td>
			   </tr>
			  </table>
			  </td>
			 </tr>
			</table>

			<p class=MsoNormal style='text-align:justify'><span lang=PT-BR><o:p>&nbsp;</o:p></span></p>

			</div>

	</div>

</div>

</section><!--fim contato-->
