
<meta charset="utf-8">
<meta name="description" content="">
<meta name="keywords" content="" />
<meta name="author" content="iuny - agência digital">
<meta name="contact" content="contato@iuny.com.br"> 
<meta name="robots" content="index,follow" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!--======= Mobile Metas =======-->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content="width=device-width">

<!--======= Favicons =======-->

<!-- website favicon -->
<link rel="shortcut icon" href="<?php print $this->baseUrl()?>/public/imgs/favicon.png">
<!-- iPhone, iPod Touch -->
<link rel="apple-touch-icon" href="<?php print $this->baseUrl()?>/public/imgs/apple-touch-icon.png">
<!-- iPhone with Retina display -->
<link rel="apple-touch-icon" sizes="114x114" href="<?php print $this->baseUrl()?>/public/imgs/apple-touch-icon-114x114.png">
<!-- iPad first and second generation -->
<link rel="apple-touch-icon" sizes="72x72" href="<?php print $this->baseUrl()?>/public/imgs/apple-touch-icon-72x72.png">
<!-- iPad with Retina display -->
<link rel="apple-touch-icon" sizes="144x144" href="<?php print $this->baseUrl()?>/public/imgs/apple-touch-icon-144x144.png">    
    
<!-- jquery -->
<script src="<?php print $this->baseUrl()?>/public/js/jquery-1.8.3.min.js"></script>
<script src="<?php print $this->baseUrl()?>/public/js/jqueryUI/jquery-ui-1.8.custom.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl()?>/public/js/jquery.maskedinput-1.3.min.js"></script>
<script type="text/javascript" src="<?php print $this->baseUrl()?>/public/js/config.js"></script>

<!-- css -->
<link rel="stylesheet" href="<?php print $this->baseUrl()?>/public/css/estilo.css">
<link rel="stylesheet" href="<?php print $this->baseUrl()?>/public/css/grid.css">
<link rel="stylesheet" href="<?php print $this->baseUrl()?>/public/css/reset.css">
<link rel="stylesheet" href="<?php print $this->baseUrl()?>/public/css/fancybox.css">
<link rel="stylesheet" href="<?php print $this->baseUrl()?>/public/css/jqueryUI/jquery-ui-1.8.1.custom.css">

<!--[if lt IE 9]>
    <script type="text/javascript" src="<?php print $this->baseUrl()?>/public/js/html5shiv.js"></script>
    <script type="text/javascript" src="<?php print $this->baseUrl()?>/public/js/selectivizr.js"></script>
    <script type="text/javascript" src="<?php print $this->baseUrl()?>/public/js/respond.js"></script>
<![endif]-->

<title>Banheiros Vrio</title>
