
<footer id="rodape" class="box_fluido clearfix">
	<div class="box">
		<div class="col12">
			<div class="col5 esq esq1 apps">
				<p>Faça o download de nosso aplicativo</p>
				<ul>
					<li><a class="google" href="" onclick="alert('Em breve os apps estarão disponíveis.');">google play</a></li>
					<li><a class="app" href="" onclick="alert('Em breve os apps estarão disponíveis.');">app store</a></li>
				</ul>
			</div>			
			
			<div class="col5 dir dir1 compartilhar">
				<p>compartilhe nas redes sociais</p>
				<ul>
                      <li class="fb">
                      	<div class="fb-like" data-href="http://www.banheirosvrio.com.br" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
                        <div id="fb-root"></div>
						<script>(function(d, s, id) {
						  var js, fjs = d.getElementsByTagName(s)[0];
						  if (d.getElementById(id)) return;
						  js = d.createElement(s); js.id = id;
						  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
						  fjs.parentNode.insertBefore(js, fjs);
						}(document, 'script', 'facebook-jssdk'));</script>
                      </li>
                      <li class="tw">
                         <a href="https://twitter.com/share" class="twitter-share-button" data-lang="pt">Tweetar</a>
                         <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                      </li>
                      <li class="gp">
                         <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script><g:plusone size="medium"></g:plusone>
                      </li>
                    </ul>
			</div>
		</div>

		<section class="col12 ass">
			<address>Tel. 81 4141.6398 | 3224.0009   |   Av. Senador Nilo Coelho, 183, Peixinhos, Olinda-PE.  <br> 
				Copyright &copy; 2014 Banheiros Vrio. Todos os direitos reservados.</address>
		</section>

	</div>
</footer>

