<!DOCTYPE html>

<html lang="pt-br"> 
<head>
<?php include_once 'includes/header.phtml';?>
</head>

<body>

<div id="geral" class="box_fluido clearfix"><!--inicio geral-->
<?php include_once 'includes/topo.phtml';?>

<section id="conteudo" class="box_fluido clearfix"><!--inicio conteudo-->
<?php print $this->layout()->conteudoSite;?> 
</section><!--fim conteudo-->

</div><!--fim geral-->
<?php  include_once 'includes/rodape.phtml';?>

</body>

<!-- scripts -->
<script src="<?php print $this->baseUrl()?>/public/js/widgets.js"></script>
<script src="<?php print $this->baseUrl()?>/public/js/bxslider.js"></script>
<script src="<?php print $this->baseUrl()?>/public/js/jquery.fancybox.js"></script>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>
</html>
